### ISSUE TITLE
xmlschema.exceptions.XMLSchemaTypeError

### ISSUE THREAD

**Issue by hmkim** [glow-mdsol/clinical_trials#2]
Hello, With example code, I got the error in below.

Could you check this issue ?

> >>> study = ClinicalStudy.from_nctid('NCT02348489')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/brandon/Downloads/src/glow-mdsol-clinical-trials/clinical_trials/clinical_study.py", line 738, in from_nctid
>     return cls(schema.to_dict(content))
>   File "/Users/brandon/miniconda3/lib/python3.6/site-packages/xmlschema/validators/xsdbase.py", line 564, in decode
>     for result in self.iter_decode(source, validation=validation, *args, **kwargs):
>   File "/Users/brandon/miniconda3/lib/python3.6/site-packages/xmlschema/validators/schema.py", line 785, in iter_decode
>     source = XMLResource(source=source, defuse=defuse, timeout=timeout, lazy=False)
>   File "/Users/brandon/miniconda3/lib/python3.6/site-packages/xmlschema/resources.py", line 240, in __init__
>     self.source = source
>   File "/Users/brandon/miniconda3/lib/python3.6/site-packages/xmlschema/resources.py", line 264, in __setattr__
>     self._root, self._document, self._text, self._url = self._fromsource(value)
>   File "/Users/brandon/miniconda3/lib/python3.6/site-packages/xmlschema/resources.py", line 339, in _fromsource
>     "string containing XML data or an URL or a file-like object is required." % type(source)
> xmlschema.exceptions.XMLSchemaTypeError: wrong type <class 'bytes'> for 'source' attribute: an ElementTree object or an Element instance or a string containing XML data or an URL or a file-like object is required.

Thanks in advance!

Hyunmin

**Comment by glow-mdsol** [comment]
Sorry, completely missed this.  Is this still present?

**Comment by hmkim** [comment]
I'll test it again and report it. Thank you.

**Comment by hmkim** [comment]
I finished the test successfully like this.
![test](https://user-images.githubusercontent.com/4966343/59618143-8d013580-9162-11e9-90ae-0b309a767087.png)
